# Generated by Django 4.2.3 on 2023-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='Contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
